name: build

on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane
  schedule:
    - cron: '0 3 * * 1,4'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: diffuse-latest-binary.jar
          path: diffuse/build/libs/diffuse-*-binary.jar
          if-no-files-found: error

      - uses: actions/cache@v2
        name: Upload base
        with:
          path: diffuse-source-file
          key: diffuse-${{ github.sha }}

      - run: cp diffuse/build/libs/diffuse-unspecified-binary.jar diffuse-source-file
        shell: bash
