name: build

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}


      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - run: ./gradlew build -Pversion=${{ steps.get_version.outputs.version }}

      - uses: actions/upload-artifact@v2
        with:
          name: diffuse-latest-binary.jar
          path: diffuse/build/libs/diffuse-*-binary.jar
          if-no-files-found: error

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: diffuse/build/libs/diffuse-*-binary.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

