name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew assemble

      - uses: actions/cache@v2
        name: Download base
        with:
          path: diffuse-source-file
          key: diffuse-${{ github.event.pull_request.base.sha }}

      - id: diffuse
        uses: usefulness/diffuse-action@v1
        with:
          old-file-path: diffuse-source-file
          new-file-path: diffuse/build/libs/diffuse-unspecified-binary.jar


